### ISSUE TITLE
onActivityResult issue

### ISSUE THREAD

**Issue by tayorh27** [wajahatkarim3/LongImageCamera#1]
Good day,

I just started using your library. Nice work.

But I can't get 2 static Strings from the LongImageActivity which are LONG_IMAGE_RESULT_CODE and IMAGE_PATH_KEY.

Any solution?

Thanks.

**Comment by wajahatkarim3** [comment]
Hello,

These are declared in LongImageActivity like this:
```java
public static final String IMAGE_PATH_KEY = "imagePathKey";
public static final int LONG_IMAGE_RESULT_CODE = 1234;
```

you can statically import these as well like 
```java
import static com.wajahatkarim3.longimagecamera.LongImageCamera.*;
```
This should solve your issue. Again, still you are facing same kind of issue, then you can use values directly instead of the variables.
